### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by AmirDraoui** [LoicGrobol/decofre#1]
Hi,
when I run decofre-infer is the output supposed to get printed on the console or should I expect it to be dumped in a file on my disk ?
The output I got on the terminal when i used decofre-infer is the text i gave as input unchanged.

**Comment by LoicGrobol** [comment]
If you did not specify an output file, it should go on the console. The input will be unchanged if no mention was detected. If you used models generated with the sanity-check config that is to be expected (since the training set is so small, it almost always converge to the majority class, viz. non-mention).

**Comment by AmirDraoui** [comment]
Okay thank you, could you please explain how to change the sanity-check config. I have been trying to change it but with no success.

**Comment by LoicGrobol** [comment]
If you follow the instructions in readme to get ANCOR data, you can train with config `datasets/ancor/train_configs/2019-07-09-noboost.jsonnet` and model-config `datasets/ancor/model_configs/2019-07-05-larger_hidden-high_drop.jsonnet` for instance. Just change the path in the command invocations
