### ISSUE TITLE
Actual training does nothing

### ISSUE THREAD

**Issue by Achuttarsing** [LoicGrobol/decofre#10]
Hi ! I would like to test the actual training but apparently it does not give any change...

I installed Decofre and Spacy then : 

1. `git clone https://github.com/LoicGrobol/decofre && cd decofre`
2. `python -m doit run -f datasets/ancor/ancor.py`
3. `decofre-train --config tests/sanity-check.jsonnet --model-config decofre/models/default.jsonnet --out-dir /path/to/an/output/directory`

Then I tried `decofre-infer /Users/adrien/decofre/loaded_model/detector.model /Users/theo/decofre/loaded_model/coref.model /Users/theo/decofre/text.txt` twice : 

1. On a long Google speech-to-text file → no change 
2. On _"Julien est un homme. Il fait du vélo."_ → no change 

In each case I can see the 2 loading bars processing but the output text is the same as the input text

I hope you can help me 

thank you

**Comment by LoicGrobol** [comment]
Hi, thanks for your interest. As mentioned in the README

> The sanity-check training config is, well, a sanity check, meant to see if DeCOFre actually runs in your environment and uses a tiny training set to make it fast. The resulting models will therefore be awful. This is normal, don't be alarmed.

In your case you don't see any change because the model did not detect any mention, which is to be expected with such a tiny training set. We have [a model for spoken French]( https://github.com/LoicGrobol/decofre/releases/tag/v0.7.0dev0) that might interest you, though.

**Comment by Achuttarsing** [comment]
nice reactivity ! thank you !
